import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-gazi-country, x-cashfree-internal-secret","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const CASHFREE_API_VERSION="2025-01-01";const CASHFREE_ORDERS_URL="https://api.cashfree.com/pg/orders";
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:corsHeaders});}
function secretKey(){const raw=Deno.env.get("SUPABASE_SECRET_KEYS");if(!raw)throw new Error("Supabase secret keys unavailable");return JSON.parse(raw)["default"] as string;}
function publishableKey(){const raw=Deno.env.get("SUPABASE_PUBLISHABLE_KEYS");return raw?JSON.parse(raw)["default"] as string:null;}
Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{status:200,headers:corsHeaders});if(req.method!=="POST")return json({ok:false,error:"Method not allowed"},405);
 const appId=Deno.env.get("CASHFREE_APP_ID"),cashfreeSecret=Deno.env.get("CASHFREE_SECRET_KEY");if(!appId||!cashfreeSecret)return json({ok:false,error:"Cashfree credentials are not configured"},500);
 const internalSecret=req.headers.get("x-cashfree-internal-secret"),isInternal=!!internalSecret&&internalSecret===cashfreeSecret;
 let body:Record<string,unknown>;try{body=await req.json();}catch{return json({ok:false,error:"Invalid JSON body"},400);}
 const paymentIntentId=typeof body.payment_intent_id==="string"?body.payment_intent_id.trim():"",cashfreeOrderId=typeof body.cashfree_order_id==="string"?body.cashfree_order_id.trim():"";if(!paymentIntentId&&!cashfreeOrderId)return json({ok:false,error:"payment_intent_id or cashfree_order_id is required"},400);
 const admin=createClient(Deno.env.get("SUPABASE_URL")!,secretKey(),{auth:{autoRefreshToken:false,persistSession:false}});
 const intentQuery=paymentIntentId?admin.from("cashfree_payment_intents").select("*").eq("id",paymentIntentId).maybeSingle():admin.from("cashfree_payment_intents").select("*").eq("cashfree_order_id",cashfreeOrderId).maybeSingle();const {data:intent,intentError}=await intentQuery;if(intentError||!intent)return json({ok:false,error:"Payment intent not found"},404);
 let userId:string|null=null;const authHeader=req.headers.get("Authorization");if(!isInternal&&authHeader?.startsWith("Bearer ")){try{const key=publishableKey();if(key){const userClient=createClient(Deno.env.get("SUPABASE_URL")!,key,{global:{headers:{Authorization:authHeader,"x-gazi-country":"IN"}}});const {data}=await userClient.auth.getUser();userId=data.user?.id??null;}}catch{/* guest */}}
 if(!isInternal&&intent.user_id&&intent.user_id!==userId)return json({ok:false,error:"Payment intent does not belong to this user"},403);
 if(intent.completed_order_id){const {data:completedOrder}=await admin.from("orders").select("order_number,customer_phone,order_status,status,country_code").eq("id",intent.completed_order_id).maybeSingle();if(completedOrder?.country_code==="IN"){await admin.functions.invoke("send-order-confirmation-sms",{body:{order_id:intent.completed_order_id,order_number:completedOrder.order_number,phone:completedOrder.customer_phone,order_status:completedOrder.order_status||completedOrder.status}});}return json({ok:true,already_completed:true,payment_intent_id:intent.id,order_id:intent.completed_order_id,order_number:completedOrder?.order_number||null});}
 if(intent.country_code!=="IN"||intent.currency!=="INR"||!Number.isFinite(Number(intent.amount))||Number(intent.amount)<=0)return json({ok:false,error:"Invalid India payment intent"},409);
 if(!intent.cashfree_order_id)return json({ok:false,error:"Cashfree order is not initialized"},409);
 const {data:claimed}=await admin.from("cashfree_payment_intents").update({status:"processing",updated_at:new Date().toISOString()}).eq("id",intent.id).in("status",["created","pending"]).is("completed_order_id",null).select("id").maybeSingle();if(!claimed){const {data:latest}=await admin.from("cashfree_payment_intents").select("status,completed_order_id").eq("id",intent.id).maybeSingle();if(latest?.completed_order_id){const {data:completedOrder}=await admin.from("orders").select("order_number").eq("id",latest.completed_order_id).maybeSingle();return json({ok:true,already_completed:true,payment_intent_id:intent.id,order_id:latest.completed_order_id,order_number:completedOrder?.order_number||null});}if(latest?.status==="processing")return json({ok:true,processing:true,payment_intent_id:intent.id},202);return json({ok:false,error:"Payment intent is not in a completable state",status:latest?.status||null},409);}
 const cfResponse=await fetch(`${CASHFREE_ORDERS_URL}/${encodeURIComponent(intent.cashfree_order_id)}`,{method:"GET",headers:{"x-api-version":CASHFREE_API_VERSION,"x-client-id":appId,"x-client-secret":cashfreeSecret,"x-request-id":crypto.randomUUID()}});const cfText=await cfResponse.text();let cf:Record<string,unknown>={};try{cf=JSON.parse(cfText);}catch{cf={raw:cfText};}
 if(!cfResponse.ok){await admin.from("cashfree_payment_intents").update({status:"created",updated_at:new Date().toISOString()}).eq("id",intent.id).eq("status","processing");return json({ok:false,error:"Cashfree order status check failed",cashfree_status:cfResponse.status,details:cf},502);}
 const orderStatus=typeof cf.order_status==="string"?cf.order_status:"";if(orderStatus!=="PAID"){const nextStatus=orderStatus==="EXPIRED"||orderStatus==="TERMINATED"?"failed":"pending";await admin.from("cashfree_payment_intents").update({status:nextStatus,updated_at:new Date().toISOString()}).eq("id",intent.id).eq("status","processing");return json({ok:true,paid:false,payment_intent_id:intent.id,order_status:orderStatus});}
 const cashfreeAmount=Number(cf.order_amount);if(cf.order_id!==intent.cashfree_order_id||!Number.isFinite(cashfreeAmount)||cashfreeAmount<=0||Math.abs(cashfreeAmount-Number(intent.amount))>0.01){await admin.from("cashfree_payment_intents").update({status:"created",updated_at:new Date().toISOString()}).eq("id",intent.id).eq("status","processing");return json({ok:false,error:"Paid amount does not match the payment intent",expected_amount:Number(intent.amount),paid_amount:cashfreeAmount},409);}if(cf.order_currency!=="INR"||intent.currency!=="INR"){await admin.from("cashfree_payment_intents").update({status:"created",updated_at:new Date().toISOString()}).eq("id",intent.id).eq("status","processing");return json({ok:false,error:"Paid currency does not match the payment intent"},409);}
 const {data:quote,error:quoteError}=await admin.rpc("calculate_cashfree_checkout_quote",{p_items:intent.items,p_coupon_code:intent.coupon_code,p_user_id:intent.user_id,p_use_referral_wallet:intent.use_referral_wallet,p_country_code:"IN"});if(quoteError||!quote?.success){await admin.from("cashfree_payment_intents").update({status:"created",updated_at:new Date().toISOString()}).eq("id",intent.id).eq("status","processing");return json({ok:false,error:"Checkout quote could not be revalidated",details:quoteError?.message||quote?.error||null},409);}
 const currentAmount=Number(quote.final_amount);if(!Number.isFinite(currentAmount)||Math.abs(currentAmount-Number(intent.amount))>0.01||Math.abs(currentAmount-cashfreeAmount)>0.01){await admin.from("cashfree_payment_intents").update({status:"created",updated_at:new Date().toISOString()}).eq("id",intent.id).eq("status","processing");return json({ok:false,error:"Checkout amount changed before order completion",intent_amount:Number(intent.amount),current_amount:currentAmount,paid_amount:cashfreeAmount},409);}
 const customer=(intent.customer_details||{}) as Record<string,unknown>;const customerName=typeof customer.customer_name==="string"?customer.customer_name:"",customerPhone=typeof customer.customer_phone==="string"?customer.customer_phone:"",specialInstructions=typeof intent.special_instructions==="string"?intent.special_instructions:"";
 const {data:atomicResult,error:atomicError}=await admin.rpc("complete_cashfree_paid_order_atomic",{p_payment_intent_id:intent.id,p_customer_name:customerName,p_customer_phone:customerPhone,p_delivery_address:intent.delivery_address,p_items:intent.items,p_coupon_code:intent.coupon_code,p_special_instructions:specialInstructions,p_user_id:intent.user_id,p_use_referral_wallet:intent.use_referral_wallet});
 if(atomicError||!atomicResult?.success){await admin.from("cashfree_payment_intents").update({status:"created",updated_at:new Date().toISOString()}).eq("id",intent.id).eq("status","processing");return json({ok:false,error:"Payment succeeded but atomic order completion failed",details:atomicError?.message||atomicResult?.error||null,payment_intent_id:intent.id},502);}
 if(intent.country_code==="IN"){await admin.functions.invoke("send-order-confirmation-sms",{body:{order_id:atomicResult.order_id,order_number:atomicResult.order_number,phone:customerPhone,order_status:"confirmed"}});}return json({ok:true,paid:true,completed:true,payment_intent_id:intent.id,order_id:atomicResult.order_id,order_number:atomicResult.order_number,amount:Number(atomicResult.amount??atomicResult.final_amount),currency:"INR"});
});
