'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type Country = 'BD' | 'IN';
type AlertRow = { combo_id:string; combo_name:string; combo_sku:string; combo_stock:number; low_stock_threshold:number; status:string; limiting_component_id:string|null; limiting_component_name:string; limiting_component_sku:string; limiting_component_stock:number; limiting_component_required:number };

export default function ComboStockAlerts(){
 const [country,setCountry]=useState<Country>('BD'); const [rows,setRows]=useState<AlertRow[]>([]); const [search,setSearch]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [updated,setUpdated]=useState<Date|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');const s=createClient();const {data,error}=await s.rpc('admin_combo_stock_alerts',{p_country:country});if(error){setError(error.message);setRows([])}else{setRows((data||[]) as AlertRow[]);setUpdated(new Date())}setLoading(false)},[country]);
 useEffect(()=>{load()},[load]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return rows.filter(r=>!q||`${r.combo_name} ${r.combo_sku} ${r.limiting_component_name} ${r.limiting_component_sku}`.toLowerCase().includes(q))},[rows,search]);
 const low=rows.filter(r=>r.status==='LOW_STOCK'), out=rows.filter(r=>r.status==='OUT_OF_STOCK'); const total=rows.reduce((n,r)=>n+r.combo_stock,0);
 return <main className="p-5 md:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-black">Combo Stock Alerts</h1><p className="mt-1 text-gray-500">Component-aware combo availability and stock health.</p></div><div className="flex gap-2"><select value={country} onChange={e=>setCountry(e.target.value as Country)} className="rounded-xl border bg-white px-4 py-3 font-semibold"><option value="BD">Bangladesh</option><option value="IN">India</option></select><button onClick={load} disabled={loading} className="rounded-xl border bg-white px-4 py-3 font-semibold hover:bg-gray-50 disabled:opacity-60">{loading?'Refreshing…':'↻ Refresh'}</button></div></div>
 <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-gray-500">Total Combo Available Stock</p><p className="mt-2 text-3xl font-black">{loading?'—':total}</p></div><div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-gray-500">Total Combos</p><p className="mt-2 text-3xl font-black text-purple-700">{loading?'—':rows.length}</p></div><div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-gray-500">Low Stock</p><p className="mt-2 text-3xl font-black text-amber-600">{loading?'—':low.length}</p></div><div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-gray-500">Out of Stock</p><p className="mt-2 text-3xl font-black text-red-600">{loading?'—':out.length}</p></div></div>
 <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search combo, SKU or component…" className="w-full rounded-xl border bg-white px-4 py-3 outline-none focus:ring-2 sm:max-w-xl"/><span className="text-sm text-gray-500">{updated?`Updated ${updated.toLocaleTimeString()}`:'Loading…'} · {filtered.length} shown</span></div>
 {error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}<button onClick={load} className="ml-3 font-bold underline">Retry</button></div>}
 <div className="mt-6 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b px-5 py-4 font-bold">Combo Alerts</div>{loading?<div className="p-8 text-center text-gray-500">Calculating component availability…</div>:filtered.length===0?<div className="p-8 text-center text-gray-500">No combo alerts found.</div>:<div className="divide-y">{filtered.map(r=><div key={r.combo_id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-black">{r.combo_name}</h2><p className="text-sm text-gray-500">SKU: {r.combo_sku||'—'}</p></div><div className={`rounded-full px-3 py-1 text-xs font-black ${r.status==='OUT_OF_STOCK'?'bg-red-100 text-red-700':r.status==='LOW_STOCK'?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700'}`}>{r.status.replaceAll('_',' ')}</div></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div><p className="text-xs text-gray-500">Available Combo Units</p><p className="text-2xl font-black">{r.combo_stock}</p></div><div><p className="text-xs text-gray-500">Limiting Component</p><p className="font-bold">{r.limiting_component_name}</p><p className="text-xs text-gray-500">{r.limiting_component_sku||'No SKU'} · Stock {r.limiting_component_stock} · Needs {r.limiting_component_required}</p></div><div><p className="text-xs text-gray-500">Threshold</p><p className="font-bold">{r.low_stock_threshold}</p></div></div></div>)}</div>}</div>
 </main>
}