'use client';

import { useEffect, useState } from 'react';
import { Plus, Edit, Trash2, Video, ExternalLink } from 'lucide-react';
import { supabase, getVisitorCountry } from '@/lib/supabase/client';
import { toast } from '@/components/site/toast-provider';
import { getYouTubeVideoId } from '@/lib/youtube';

type VideoRow = { id:string; country_code:'BD'|'IN'; title:string; description:string|null; youtube_url:string; thumbnail_url:string|null; category:string|null; display_order:number; is_active:boolean };
type FormState = { country_code:'BD'|'IN'; title:string; description:string; youtube_url:string; thumbnail_url:string; category:string; display_order:string; is_active:boolean };
const blank:FormState={country_code:'BD',title:'',description:'',youtube_url:'',thumbnail_url:'',category:'চাষাবাদ',display_order:'0',is_active:true};

export default function AdminVideosPage(){
 const [rows,setRows]=useState<VideoRow[]>([]),[loading,setLoading]=useState(true),[editing,setEditing]=useState<VideoRow|null>(null),[open,setOpen]=useState(false),[form,setForm]=useState<FormState>(blank);
 const load=async()=>{setLoading(true);const {data}=await supabase.from('videos').select('*').order('country_code').order('display_order');setRows((data||[]) as VideoRow[]);setLoading(false)};
 useEffect(()=>{load()},[]);
 const edit=(v:VideoRow)=>{setEditing(v);setForm({country_code:v.country_code,title:v.title,description:v.description||'',youtube_url:v.youtube_url,thumbnail_url:v.thumbnail_url||'',category:v.category||'',display_order:String(v.display_order),is_active:v.is_active});setOpen(true)};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!getYouTubeVideoId(form.youtube_url)||!form.title.trim()){toast('সঠিক YouTube URL ও Title দিন','error');return}const payload={...form,title:form.title.trim(),description:form.description.trim()||null,youtube_url:form.youtube_url.trim(),thumbnail_url:form.thumbnail_url.trim()||null,category:form.category.trim()||null,display_order:Number(form.display_order)||0};const r=editing?await supabase.from('videos').update(payload).eq('id',editing.id):await supabase.from('videos').insert(payload);if(r.error){toast(r.error.message,'error');return}toast(editing?'ভিডিও আপডেট হয়েছে':'ভিডিও যোগ হয়েছে');setOpen(false);setEditing(null);load()};
 const remove=async(id:string)=>{if(!confirm('ভিডিওটি মুছে ফেলতে চান?'))return;const r=await supabase.from('videos').delete().eq('id',id);if(r.error){toast(r.error.message,'error');return}toast('ভিডিও মুছে ফেলা হয়েছে');load()};
 if(loading)return <div className="h-64 animate-pulse rounded-2xl bg-secondary"/>;
 return <div><div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-black">ভিডিও ম্যানেজমেন্ট</h1><p className="mt-1 text-sm text-muted-foreground">YouTube URL, title, description, thumbnail ও display order পরিচালনা করুন।</p></div><button onClick={()=>{setEditing(null);setForm({...blank,country_code:getVisitorCountry()});setOpen(true)}} className="flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground"><Plus className="h-4 w-4"/>নতুন ভিডিও</button></div>
 <div className="grid gap-4 lg:grid-cols-2">{rows.map(v=><div key={v.id} className="rounded-2xl border border-border bg-card p-4 shadow-sm"><div className="flex items-start gap-4"><div className="flex h-16 w-24 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-secondary">{v.thumbnail_url?<img src={v.thumbnail_url} alt="" className="h-full w-full object-cover"/>:<Video className="h-7 w-7 text-primary"/>}</div><div className="min-w-0 flex-1"><div className="mb-1 flex flex-wrap gap-2"><span className="rounded-full bg-primary/10 px-2 py-1 text-[10px] font-bold text-primary">{v.country_code==='IN'?'🇮🇳 India':'🇧🇩 Bangladesh'}</span><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${v.is_active?'bg-green-50 text-green-600':'bg-red-50 text-red-600'}`}>{v.is_active?'Active':'Inactive'}</span></div><h2 className="truncate font-black">{v.title}</h2><p className="mt-1 line-clamp-2 text-xs text-muted-foreground">{v.description||'No description'}</p><div className="mt-2 flex items-center gap-3 text-[11px] text-muted-foreground"><span>Order {v.display_order}</span><a href={v.youtube_url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-primary hover:underline">YouTube<ExternalLink className="h-3 w-3"/></a></div></div><div className="flex gap-1"><button onClick={()=>edit(v)} className="rounded-lg p-2 hover:bg-secondary"><Edit className="h-4 w-4"/></button><button onClick={()=>remove(v.id)} className="rounded-lg p-2 text-destructive hover:bg-destructive/10"><Trash2 className="h-4 w-4"/></button></div></div></div>)}{rows.length===0&&<div className="rounded-2xl border border-dashed border-border p-12 text-center text-muted-foreground lg:col-span-2">এখনো কোনো ভিডিও যোগ করা হয়নি।</div>}</div>
 {open&&<div className="fixed inset-0 z-[100] flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/50" onClick={()=>setOpen(false)}/><div className="relative z-10 max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-background p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-black">{editing?'ভিডিও এডিট':'নতুন ভিডিও'}</h2><p className="mt-1 text-xs text-muted-foreground">YouTube link paste করুন, player automatically embed হবে।</p></div><button onClick={()=>setOpen(false)} className="rounded-xl bg-secondary px-3 py-2">বন্ধ</button></div><form onSubmit={save} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><div><label className="mb-1 block text-sm font-bold">Country</label><select value={form.country_code} onChange={e=>setForm({...form,country_code:e.target.value as 'BD'|'IN'})} className="input-bangla"><option value="BD">🇧🇩 Bangladesh</option><option value="IN">🇮🇳 India</option></select></div><div><label className="mb-1 block text-sm font-bold">Category</label><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="input-bangla" placeholder="চাষাবাদ"/></div></div><div><label className="mb-1 block text-sm font-bold">Video Title *</label><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="input-bangla" placeholder="টমেটো বীজ বপনের সঠিক পদ্ধতি"/></div><div><label className="mb-1 block text-sm font-bold">Video Description</label><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="input-bangla min-h-28" placeholder="ভিডিওতে কী শেখানো হয়েছে..."/></div><div><label className="mb-1 block text-sm font-bold">YouTube URL *</label><input required value={form.youtube_url} onChange={e=>setForm({...form,youtube_url:e.target.value})} className="input-bangla" placeholder="https://www.youtube.com/watch?v=..."/></div><div><label className="mb-1 block text-sm font-bold">Custom Thumbnail URL</label><input value={form.thumbnail_url} onChange={e=>setForm({...form,thumbnail_url:e.target.value})} className="input-bangla" placeholder="Optional"/></div><div className="grid gap-4 sm:grid-cols-2"><div><label className="mb-1 block text-sm font-bold">Display Order</label><input type="number" value={form.display_order} onChange={e=>setForm({...form,display_order:e.target.value})} className="input-bangla"/></div><label className="flex items-center gap-2 self-end pb-2 text-sm font-bold"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/>Active</label></div><button type="submit" className="w-full rounded-xl bg-primary py-3 font-black text-primary-foreground">{editing?'আপডেট করুন':'ভিডিও যোগ করুন'}</button></form></div></div>}
 </div>;
}
