'use client';

import { useState } from 'react';
import { supabase } from '@/lib/supabase/client';
import { Search, Loader2, Package, CheckCircle2, MapPin, CalendarDays, Truck, RotateCcw, ShoppingCart, ShieldCheck, ArrowRight } from 'lucide-react';
import { formatPrice } from '@/lib/data';
import type { Order, OrderItem } from '@/lib/supabase/types';
import { useLang } from '@/components/site/language-provider';
import Link from 'next/link';

const STATUS_LABELS: Record<string, { bn: string; en: string }> = {
  pending: { bn: 'অর্ডার গৃহীত', en: 'Order Received' }, confirmed: { bn: 'কনফার্মড', en: 'Confirmed' }, processing: { bn: 'প্রসেসিং', en: 'Processing' }, packed: { bn: 'প্যাক করা হয়েছে', en: 'Packed' }, shipped: { bn: 'শিপড', en: 'Shipped' }, delivered: { bn: 'ডেলিভার হয়েছে', en: 'Delivered' }, cancelled: { bn: 'বাতিল', en: 'Cancelled' }, returned: { bn: 'ফেরত', en: 'Returned' },
};
const STATUS_STEPS = ['pending', 'confirmed', 'processing', 'packed', 'shipped', 'delivered'];

export default function TrackOrderPage() {
  const [orderNumber, setOrderNumber] = useState(''); const [phone, setPhone] = useState(''); const [order, setOrder] = useState<Order | null>(null); const [items, setItems] = useState<OrderItem[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [searched, setSearched] = useState(false); const { lang, t } = useLang();
  const handleSearch = async (e: React.FormEvent) => { e.preventDefault(); setError(''); setOrder(null); setItems([]); if (!orderNumber || !phone) { setError(t('অর্ডার নম্বর ও ফোন নম্বর দিন', 'Enter order number and phone number')); return; } setLoading(true); setSearched(true); try { const { data, error: rpcError } = await supabase.rpc('track_order', { p_order_number: orderNumber.trim().toUpperCase(), p_customer_phone: phone.replace(/[^0-9]/g, '') }); if (rpcError) throw rpcError; if (!data) { setError(t('অর্ডার পাওয়া যায়নি। অর্ডার নম্বর ও ফোন নম্বর ঠিক আছে কিনা চেক করুন।', 'Order not found. Please check order number and phone number.')); return; } setOrder(data.order as Order); setItems((data.items || []) as OrderItem[]); } catch { setError(t('অর্ডার খুঁজতে সমস্যা হয়েছে', 'Error searching for order')); } finally { setLoading(false); } };
  const currentStepIdx = order ? STATUS_STEPS.indexOf(order.status) : -1;
  return (
    <main className="min-h-screen bg-gradient-to-b from-primary/[0.045] via-background to-background px-4 py-8 sm:py-12">
      <div className="mx-auto max-w-5xl">
        <div className="mb-2 flex items-center justify-center gap-2 text-[10px] font-black uppercase tracking-[0.2em] text-primary sm:text-xs"><span>GAZI SEED</span><span className="h-1 w-1 rounded-full bg-primary/50" /><span>{t('অর্ডার জার্নি', 'Order Journey')}</span></div>
        <div className="mx-auto mb-7 grid max-w-2xl grid-cols-4 gap-2 sm:gap-3" aria-label={t('অর্ডারের ধাপ', 'Order journey')}>
          {[['cart', t('কার্ট', 'Cart')], ['checkout', t('চেকআউট', 'Checkout')], ['confirmation', t('কনফার্মেশন', 'Confirmation')], ['tracking', t('ট্র্যাকিং', 'Tracking')]].map(([key, label], index) => { const active = index === 3; return <div key={key} className="flex items-center gap-2"><div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-xs font-black ${active ? 'bg-primary text-primary-foreground shadow-sm' : 'bg-secondary text-muted-foreground'}`}>{index + 1}</div><div className={`hidden text-left text-[11px] font-bold sm:block ${active ? 'text-foreground' : 'text-muted-foreground'}`}>{label}</div>{index < 3 && <div className={`hidden h-px flex-1 sm:block ${index < 3 ? 'bg-primary/40' : 'bg-border'}`} />}</div>; })}
        </div>

        <div className="mb-8 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/10"><Package className="h-7 w-7 text-primary" /></div><p className="mt-4 text-xs font-semibold uppercase tracking-[0.2em] text-primary">{t('ডেলিভারি ট্র্যাকিং', 'Delivery Tracking')}</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">{t('অর্ডার ট্র্যাকিং', 'Order Tracking')}</h1><p className="mx-auto mt-2 max-w-xl text-sm text-muted-foreground">{t('অর্ডার নম্বর ও মোবাইল নম্বর দিয়ে আপনার অর্ডারের বর্তমান অবস্থা দেখুন।', 'Enter your order number and mobile number to see the latest delivery status.')}</p></div>
        <form onSubmit={handleSearch} className="mx-auto mb-8 max-w-3xl rounded-[1.75rem] border border-primary/10 bg-card p-5 shadow-[0_20px_60px_-35px_hsl(var(--primary)/0.45)] sm:p-7"><div className="grid gap-4 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><div><label className="mb-2 block text-sm font-semibold">{t('অর্ডার নম্বর *', 'Order Number *')}</label><input type="text" value={orderNumber} onChange={(e) => setOrderNumber(e.target.value)} className="input-bangla min-h-12 rounded-xl" placeholder="GSXXXXXX" required /></div><div><label className="mb-2 block text-sm font-semibold">{t('মোবাইল নম্বর *', 'Mobile Number *')}</label><input type="tel" inputMode="tel" value={phone} onChange={(e) => setPhone(e.target.value)} className="input-bangla min-h-12 rounded-xl" placeholder="01XXXXXXXXX" required /></div><button type="submit" disabled={loading} className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-primary px-6 font-semibold text-primary-foreground shadow-sm transition hover:-translate-y-0.5 hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/50 focus-visible:ring-offset-2 disabled:opacity-50">{loading ? <Loader2 className="h-5 w-5 animate-spin" /> : <><Search className="h-5 w-5" />{t('খুঁজুন', 'Track')}</>}</button></div>{error && <p role="alert" className="mt-4 rounded-xl border border-destructive/15 bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}</form>
        {order && <div className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]">
          <div className="space-y-6">
            <section className="rounded-[1.75rem] border border-primary/10 bg-card p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{t('অর্ডার নম্বর', 'Order Number')}</p><p className="mt-1 text-xl font-bold text-primary">{order.order_number}</p></div><div className="flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1.5 text-xs font-semibold text-primary"><CalendarDays className="h-4 w-4" />{new Date(order.created_at).toLocaleDateString(lang === 'en' ? 'en-US' : 'bn-BD')}</div></div>
              {order.status === 'cancelled' || order.status === 'returned' ? <div className="mt-7 flex items-center gap-3 rounded-2xl bg-destructive/10 p-4"><RotateCcw className="h-6 w-6 text-destructive" /><div><p className="font-bold text-destructive">{lang === 'en' ? STATUS_LABELS[order.status].en : STATUS_LABELS[order.status].bn}</p><p className="text-xs text-muted-foreground">{t('এই অর্ডারের স্বাভাবিক ডেলিভারি প্রক্রিয়া বন্ধ রয়েছে।', 'The normal delivery journey for this order has stopped.')}</p></div></div> : <div className="mt-8"><div className="relative hidden sm:block"><div className="absolute left-[8%] right-[8%] top-4 h-1 rounded-full bg-secondary" /><div className="absolute left-[8%] top-4 h-1 rounded-full bg-primary transition-all" style={{ width: `${Math.max(0, currentStepIdx) / (STATUS_STEPS.length - 1) * 84}%` }} /><div className="relative grid grid-cols-6 gap-1">{STATUS_STEPS.map((step, idx) => <div key={step} className="flex flex-col items-center text-center"><div className={`z-10 flex h-9 w-9 items-center justify-center rounded-full border-4 border-card text-xs font-bold ${idx <= currentStepIdx ? 'bg-primary text-primary-foreground' : 'bg-secondary text-muted-foreground'}`}>{idx < currentStepIdx ? <CheckCircle2 className="h-4 w-4" /> : idx + 1}</div><span className={`mt-2 text-[10px] font-medium ${idx <= currentStepIdx ? 'text-primary' : 'text-muted-foreground'}`}>{lang === 'en' ? STATUS_LABELS[step].en : STATUS_LABELS[step].bn}</span></div>)}</div></div><div className="space-y-3 sm:hidden">{STATUS_STEPS.map((step, idx) => <div key={step} className="flex items-center gap-3"><div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-xs font-bold ${idx <= currentStepIdx ? 'bg-primary text-primary-foreground' : 'bg-secondary text-muted-foreground'}`}>{idx < currentStepIdx ? '✓' : idx + 1}</div><span className={`text-sm ${idx === currentStepIdx ? 'font-bold text-primary' : 'text-muted-foreground'}`}>{lang === 'en' ? STATUS_LABELS[step].en : STATUS_LABELS[step].bn}</span></div>)}</div></div>}
            </section>
            <section className="rounded-[1.75rem] border border-border/70 bg-card p-5 shadow-sm sm:p-7"><div className="mb-4 flex items-center gap-2"><Truck className="h-5 w-5 text-primary" /><h2 className="font-bold">{t('অর্ডার আইটেম', 'Order Items')}</h2></div><div className="space-y-2">{items.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-2xl border border-border/60 bg-background/70 p-3"><div className="h-14 w-14 overflow-hidden rounded-xl bg-secondary/30">{item.image && <img src={item.image} alt={item.product_name} className="h-full w-full object-cover" />}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.product_name}</p><p className="text-xs text-muted-foreground">{item.quantity} × {formatPrice(item.unit_price)}</p></div><span className="font-bold">{formatPrice(item.total_price)}</span></div>)}</div><div className="mt-5 space-y-2 border-t border-border pt-4 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">{t('সাবটোটাল', 'Subtotal')}</span><span>{formatPrice(order.subtotal)}</span></div><div className="flex justify-between"><span className="text-muted-foreground">{t('ডেলিভারি চার্জ', 'Delivery Charge')}</span><span>{formatPrice(order.delivery_charge)}</span></div>{order.discount > 0 && <div className="flex justify-between"><span className="text-muted-foreground">{t('ছাড়', 'Discount')}</span><span>-{formatPrice(order.discount)}</span></div>}<div className="flex justify-between border-t border-border pt-3 text-lg font-bold"><span>{t('মোট', 'Total')}</span><span className="text-primary">{formatPrice(order.grand_total)}</span></div></div></section>
          </div>
          <aside className="h-fit rounded-[1.75rem] border border-border/70 bg-card p-5 shadow-sm sm:p-7"><div className="flex items-center gap-2"><MapPin className="h-5 w-5 text-primary" /><h2 className="font-bold">{t('ডেলিভারি তথ্য', 'Delivery Information')}</h2></div><div className="mt-5 space-y-4 text-sm"><div><p className="text-xs text-muted-foreground">{t('নাম', 'Name')}</p><p className="mt-1 font-semibold">{order.customer_name}</p></div><div><p className="text-xs text-muted-foreground">{t('ফোন', 'Phone')}</p><p className="mt-1 font-semibold">{order.customer_phone}</p></div><div><p className="text-xs text-muted-foreground">{t('ঠিকানা', 'Address')}</p><p className="mt-1 leading-6">{order.delivery_address}</p></div><div><p className="text-xs text-muted-foreground">{t('এলাকা', 'Area')}</p><p className="mt-1 font-medium">{order.delivery_zone_name}</p></div></div></aside>
        </div>}
        {searched && !order && !loading && !error && <div className="mx-auto max-w-2xl rounded-[1.75rem] border border-border bg-card p-12 text-center shadow-sm"><Package className="mx-auto mb-4 h-16 w-16 text-muted-foreground/30" /><p className="font-semibold">{t('অর্ডার পাওয়া যায়নি', 'Order not found')}</p><p className="mt-1 text-sm text-muted-foreground">{t('তথ্যগুলো আবার যাচাই করে চেষ্টা করুন।', 'Please verify your details and try again.')}</p></div>}
        <div className="mt-8 grid gap-3 sm:grid-cols-2"><Link href="/all-products" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-border bg-card px-5 text-sm font-bold transition hover:border-primary/30 hover:bg-primary/[0.04] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/40 focus-visible:ring-offset-2"><ShoppingCart className="h-4 w-4" />{t('শপিং চালিয়ে যান', 'Continue Shopping')}</Link><Link href="/contact" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-primary px-5 text-sm font-bold text-primary-foreground shadow-sm transition hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/50 focus-visible:ring-offset-2"><ShieldCheck className="h-4 w-4" />{t('সহায়তা দরকার?', 'Need help?')}<ArrowRight className="h-4 w-4" /></Link></div>
      </div>
    </main>
  );
}
