// Shared translations for existing bilingual storefront labels.
export const STOREFRONT_HINDI: Record<string, string> = {
  'Vegetable Seed': 'सब्ज़ियों के बीज',
  'Hot Chili Pepper Seeds': 'तीखी मिर्च के बीज',
  'Chili Pepper Seeds': 'मिर्च के बीज',
  'Long Chili / Line Pepper': 'लंबी मिर्च',
  'Premium Red Rose Flower Seeds': 'लाल गुलाब के बीज',
  'Not specified': 'निर्दिष्ट नहीं',
  '1 gram': '1 ग्राम',
  '10g*': '10 ग्राम*',

  'Home': 'होम', 'Categories': 'श्रेणियाँ', 'Products': 'उत्पाद', 'Combo': 'कॉम्बो',
  'Offers': 'ऑफ़र', 'Guides': 'खेती गाइड', 'Videos': 'वीडियो', 'Delivery Charge': 'डिलीवरी शुल्क',
  'About': 'हमारे बारे में', 'Contact': 'संपर्क', 'Search': 'खोजें', 'Wishlist': 'पसंदीदा',
  'Account': 'खाता', 'Cart': 'कार्ट', 'Select language': 'भाषा चुनें', 'Language': 'भाषा',
  'Better Seeds, Greener Future | GAZI SEED': 'बेहतर बीज, हरित भविष्य | GAZI SEED',
  'Search products...': 'उत्पाद खोजें...', 'Search products': 'उत्पाद खोजें',
  'Open search': 'खोज खोलें', 'Account / Login': 'खाता / लॉगिन',
  'Search seeds, products or categories...': 'बीज, उत्पाद या श्रेणियाँ खोजें...',
  'Searching...': 'खोज रहे हैं...', 'Related products': 'संबंधित उत्पाद',
  'View all search results': 'सभी खोज परिणाम देखें', 'No matching products found': 'कोई उत्पाद नहीं मिला',
  'Search all products': 'सभी उत्पाद खोजें', 'Search products, seeds and categories': 'उत्पाद, बीज और श्रेणियाँ खोजें',
  'Search products & seeds...': 'उत्पाद और बीज खोजें...', 'Secure Shopping': 'सुरक्षित खरीदारी',
  'Trusted ordering': 'विश्वसनीय ऑर्डर प्रक्रिया', 'Nationwide Delivery': 'पूरे देश में डिलीवरी',
  'Easy, reliable delivery': 'आसान, विश्वसनीय डिलीवरी', 'Track Your Order': 'अपना ऑर्डर ट्रैक करें',
  'Check delivery status': 'डिलीवरी की स्थिति देखें', 'Quick Links': 'त्वरित लिंक',
  'Customer Service': 'ग्राहक सेवा', 'Track Order': 'ऑर्डर ट्रैक करें',
  'Privacy Policy': 'गोपनीयता नीति', 'Terms & Conditions': 'नियम और शर्तें',
  'Shipping Policy': 'शिपिंग नीति', 'Return & Refund': 'वापसी और रिफंड',
  'All rights reserved.': 'सर्वाधिकार सुरक्षित।', 'Better seeds for better farming.': 'बेहतर खेती के लिए बेहतर बीज।',
  'Could not load this product': 'यह उत्पाद लोड नहीं हो सका', 'Product not found': 'उत्पाद नहीं मिला',
  'The product could not be loaded due to a network or data issue. Please try again.': 'नेटवर्क या डेटा की समस्या के कारण उत्पाद लोड नहीं हुआ। फिर प्रयास करें।',
  'This product is not available for this country or the link is invalid.': 'यह उत्पाद इस देश में उपलब्ध नहीं है या लिंक गलत है।',
  'Try again': 'फिर प्रयास करें', 'View all products': 'सभी उत्पाद देखें',
  'Product is out of stock': 'उत्पाद स्टॉक में नहीं है', 'Added to cart': 'कार्ट में जोड़ा गया',
  'Login to add to wishlist': 'पसंदीदा में जोड़ने के लिए लॉगिन करें',
  'Added to wishlist': 'पसंदीदा में जोड़ा गया', 'Removed from wishlist': 'पसंदीदा से हटाया गया',
  'Enter phone number': 'मोबाइल नंबर दर्ज करें', 'Failed to save': 'सहेजा नहीं जा सका',
  'You will be notified when in stock': 'स्टॉक आने पर आपको सूचित किया जाएगा',
  'Seed Type': 'बीज का प्रकार', 'Variety': 'किस्म', 'Brand': 'ब्रांड', 'Origin': 'उत्पत्ति',
  'Season': 'मौसम', 'Planting Season': 'बुवाई का मौसम', 'Germination Time': 'अंकुरण का समय',
  'Germination Rate': 'अंकुरण दर', 'Harvest Time': 'फसल का समय', 'Plant Spacing': 'पौधों की दूरी',
  'Planting Depth': 'बुवाई की गहराई', 'Sunlight': 'धूप', 'Water Requirement': 'पानी की आवश्यकता',
  'Soil Type': 'मिट्टी का प्रकार', 'Growing Location': 'खेती का स्थान', 'Packet Weight': 'पैकेट का वजन',
  'Seed Quantity': 'बीज की संख्या', 'Expected Yield': 'संभावित उपज',
  '100% Original Seeds': '100% असली बीज', 'Remove from wishlist': 'पसंदीदा से हटाएँ',
  'Add to wishlist': 'पसंदीदा में जोड़ें', 'New Product': 'नया उत्पाद', 'Verified Reviews': 'सत्यापित समीक्षाएँ',
  'Current Price': 'वर्तमान मूल्य', 'OFF': 'छूट', 'Select Packet or Variety': 'पैकेट या किस्म चुनें',
  '🔥 BUY MORE, SAVE MORE': '🔥 अधिक खरीदें, अधिक बचाएँ',
  'Buy more packs and save more — the best eligible offer applies automatically.': 'अधिक पैकेट खरीदें और बचत करें। सबसे अच्छा पात्र ऑफ़र अपने आप लागू होता है।',
  'BEST VALUE': 'सबसे किफायती', 'ACTIVE': 'लागू', 'PACKETS': 'पैकेट', 'TOTAL': 'कुल',
  'per pack': 'प्रति पैकेट', 'SAVE': 'बचत', 'Best price applied automatically': 'सबसे अच्छा मूल्य अपने आप लागू हुआ',
  'In Stock': 'स्टॉक में उपलब्ध', 'Out of Stock': 'स्टॉक में नहीं',
  'Decrease quantity': 'मात्रा घटाएँ', 'Increase quantity': 'मात्रा बढ़ाएँ', 'Total Price': 'कुल मूल्य',
  'Add to Cart': 'कार्ट में जोड़ें', 'Buy Now': 'अभी खरीदें',
  'Want to be notified when back in stock?': 'स्टॉक आने पर सूचना चाहिए?',
  'Notify me': 'मुझे सूचित करें', 'Mobile number': 'मोबाइल नंबर',
  '11-digit mobile number *': '11 अंकों का मोबाइल नंबर *', 'Activate Notification': 'सूचना चालू करें',
  'You will be notified via SMS as soon as it is in stock.': 'स्टॉक आते ही आपको SMS से सूचित किया जाएगा।',
  'Home Delivery Nationwide': 'पूरे देश में होम डिलीवरी', 'Cash on Delivery': 'कैश ऑन डिलीवरी',
  '100% Pure & Tested': '100% शुद्ध और परीक्षित', 'Special Bundle Deal': 'विशेष बंडल ऑफ़र',
  'pcs bundle': 'पैकेट का बंडल', 'Add': 'जोड़ें', 'Product information': 'उत्पाद की जानकारी',
  'Description': 'विवरण', 'Seed Specs': 'बीज की जानकारी', 'Cultivation Guide': 'खेती गाइड',
  'Reviews': 'समीक्षाएँ', 'FAQ': 'अक्सर पूछे जाने वाले प्रश्न', 'Product Description': 'उत्पाद विवरण',
  'Seed Specifications': 'बीज की विशेषताएँ', 'Cultivation Method': 'खेती की विधि',
  'Storage Method': 'भंडारण की विधि', 'Ratings': 'रेटिंग', 'Verified Buyer': 'सत्यापित खरीदार',
  'Admin Reply:': 'विक्रेता का जवाब:', 'No reviews yet. Be the first to review!': 'अभी कोई समीक्षा नहीं है। पहली समीक्षा लिखें!',
  'You may also like these seeds': 'आपको ये बीज भी पसंद आ सकते हैं',
  'Total items price': 'उत्पादों का कुल मूल्य', 'Add to cart': 'कार्ट में जोड़ें', 'Order Now': 'अभी ऑर्डर करें',
  'Your cart is empty': 'आपका कार्ट खाली है', 'Choose your favorite seeds and start your order today.': 'अपने पसंदीदा बीज चुनें और आज ही ऑर्डर करें।',
  'Start Shopping': 'खरीदारी शुरू करें', 'items in your cart': 'उत्पाद आपके कार्ट में', 'Secure shopping': 'सुरक्षित खरीदारी',
  'Remove': 'हटाएँ', 'each': 'प्रत्येक', 'Continue Shopping': 'खरीदारी जारी रखें',
  'Order Summary': 'ऑर्डर का सारांश', 'Total with your savings': 'बचत के साथ कुल राशि',
  'Original Price': 'मूल मूल्य', 'Discount': 'छूट', 'Offer Price': 'ऑफ़र मूल्य',
  'Determined at checkout': 'चेकआउट पर निर्धारित', 'Total': 'कुल', 'You save': 'आपकी बचत',
  'Delivery': 'डिलीवरी', 'Secure': 'सुरक्षित', 'Checkout': 'चेकआउट',
  'Payment received, but the order is still being finalized. Please wait a moment and try again.': 'भुगतान मिला है, लेकिन ऑर्डर पूरा किया जा रहा है। थोड़ी देर बाद फिर प्रयास करें।',
  'Payment was not completed. Please try again.': 'भुगतान पूरा नहीं हुआ। फिर प्रयास करें।',
  'Payment could not be verified.': 'भुगतान सत्यापित नहीं हुआ।',
  'Unable to verify the payment. Please try again.': 'भुगतान सत्यापित नहीं किया जा सका। फिर प्रयास करें।',
  'Free delivery unlocked': 'मुफ़्त डिलीवरी उपलब्ध', 'Applicable delivery charge added': 'डिलीवरी शुल्क जोड़ा गया',
  'Coupon not found': 'कूपन नहीं मिला', 'Coupon limit reached': 'कूपन की सीमा पूरी हुई',
  'Coupon not active yet': 'कूपन अभी चालू नहीं है', 'Coupon expired': 'कूपन समाप्त हो गया',
  'Unable to start online payment. Please try again.': 'ऑनलाइन भुगतान शुरू नहीं हुआ। फिर प्रयास करें।',
  'Name is required': 'नाम आवश्यक है', 'Enter a valid 10-digit Indian mobile number': 'भारत का सही 10 अंकों का मोबाइल नंबर दर्ज करें',
  'Enter a valid phone number': 'सही मोबाइल नंबर दर्ज करें',
  'Enter a complete Indian address and 6-digit PIN code': 'भारत का पूरा पता और 6 अंकों का PIN कोड दर्ज करें',
  'Enter full address': 'पूरा पता दर्ज करें', 'Cart is empty': 'कार्ट खाली है',
  'Order failed. Please try again.': 'ऑर्डर नहीं हुआ। फिर प्रयास करें।', 'Add items to cart first': 'पहले कार्ट में उत्पाद जोड़ें',
  'Shop Now': 'अभी खरीदें', 'Secure checkout': 'सुरक्षित चेकआउट', 'Complete your checkout': 'अपना चेकआउट पूरा करें',
  'Confirm your delivery details, apply any coupon or wallet credit, then place your order.': 'डिलीवरी की जानकारी जाँचें, कूपन या वॉलेट राशि लागू करें और ऑर्डर करें।',
  'Confirmation': 'पुष्टि', 'Quick select': 'जल्दी चुनें', 'Saved addresses': 'सहेजे गए पते',
  'Default address': 'डिफ़ॉल्ट पता', 'Delivery information': 'डिलीवरी की जानकारी',
  'Where your order will be delivered': 'आपका ऑर्डर यहाँ पहुँचाया जाएगा', 'Your name': 'आपका नाम',
  'e.g. Md. Ariful Islam': 'उदा. मोहम्मद आरिफ़ुल इस्लाम', 'Phone number': 'मोबाइल नंबर',
  'Special instructions': 'विशेष निर्देश', 'Add any special delivery instructions...': 'डिलीवरी के विशेष निर्देश लिखें...',
  'Coupon code': 'कूपन कोड', 'Have a discount code? Apply it here.': 'छूट का कोड है? यहाँ लागू करें।',
  'Enter coupon code': 'कूपन कोड दर्ज करें', 'Apply': 'लागू करें', 'Your referral wallet': 'आपका रेफ़रल वॉलेट',
  'Checking your wallet balance...': 'वॉलेट की राशि जाँची जा रही है...', 'Available': 'उपलब्ध',
  'Use wallet credit': 'वॉलेट राशि उपयोग करें', 'Order summary': 'ऑर्डर का सारांश',
  'Payment method': 'भुगतान का तरीका', 'How would you like to pay?': 'आप कैसे भुगतान करना चाहेंगे?',
  'Online payment': 'ऑनलाइन भुगतान', 'COD is not available for this order.': 'इस ऑर्डर पर COD उपलब्ध नहीं है।',
  'Subtotal': 'उप-कुल', 'Coupon discount': 'कूपन की छूट', 'Free': 'मुफ़्त',
  'COD advance': 'COD अग्रिम राशि', 'Due on delivery': 'डिलीवरी पर देय', 'Wallet credit': 'वॉलेट राशि',
  'Final payable amount': 'अंतिम देय राशि', 'Pay COD advance': 'COD अग्रिम राशि चुकाएँ',
  'Pay online': 'ऑनलाइन भुगतान करें', 'Confirm order': 'ऑर्डर की पुष्टि करें', 'Nationwide': 'पूरे देश में',
  'Secure order processing': 'सुरक्षित ऑर्डर प्रक्रिया',
  'Your details are handled securely throughout checkout.': 'चेकआउट के दौरान आपकी जानकारी सुरक्षित रहती है।',
  'Payable': 'देय राशि', 'Place order': 'ऑर्डर करें', 'Your Cart': 'आपका कार्ट', 'items': 'उत्पाद',
  'Close cart': 'कार्ट बंद करें', 'Remove product': 'उत्पाद हटाएँ', 'View cart': 'कार्ट देखें',
  'India': 'भारत', 'Bangladesh': 'बांग्लादेश', 'Dhaka, Bangladesh': 'ढाका, बांग्लादेश',
  'India Store': 'भारत स्टोर', 'India Guides': 'भारत खेती गाइड', 'Vegetable Seeds': 'सब्ज़ी के बीज',
  'Flower Seeds': 'फूलों के बीज', '10 g': '10 ग्राम', 'Approximately 100 seeds': 'लगभग 100 बीज',
  'Varies by packet': 'पैकेट के अनुसार बदलता है', 'See packet label': 'पैकेट का लेबल देखें',
};
