'use client';

import { useState } from 'react';
import { createOrder } from '@/lib/checkout';

export default function CheckoutPage() {
  const [loading, setLoading] = useState(false); const [message, setMessage] = useState('');
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setLoading(true); setMessage(''); const f = new FormData(e.currentTarget); try { const result = await createOrder({ country: 'BD', items: [{ productId: String(f.get('productId') || ''), quantity: Number(f.get('quantity') || 1) }], customer: { name: String(f.get('name')), phone: String(f.get('phone')), email: String(f.get('email') || ''), address: String(f.get('address')), district: String(f.get('district') || ''), area: String(f.get('area') || '') }, couponCode: String(f.get('coupon') || '') || undefined, paymentMethod: 'cod' }); setMessage(`Order created: ${result?.order_number ?? result?.order_id ?? 'success'}`); } catch (err) { setMessage(err instanceof Error ? err.message : 'Unable to create order'); } finally { setLoading(false); } }
  return <main className="min-h-screen bg-[#f7f8f4] px-4 py-10"><div className="mx-auto max-w-3xl rounded-3xl border bg-white p-6 shadow-lg md:p-10"><p className="font-bold text-[#1f6b3b]">GAZI SEED</p><h1 className="mt-2 text-3xl font-black">Secure Checkout</h1><p className="mt-2 text-sm text-gray-500">Guest checkout is supported. Stock, coupon and order creation are validated server-side.</p><form onSubmit={submit} className="mt-8 grid gap-4 md:grid-cols-2"><input name="name" required placeholder="Full name" className="rounded-xl border px-4 py-3"/><input name="phone" required placeholder="Phone number" className="rounded-xl border px-4 py-3"/><input name="email" type="email" placeholder="Email (optional)" className="rounded-xl border px-4 py-3"/><input name="district" placeholder="District" className="rounded-xl border px-4 py-3"/><input name="area" placeholder="Area" className="rounded-xl border px-4 py-3"/><input name="productId" required placeholder="Product ID" className="rounded-xl border px-4 py-3"/><input name="quantity" type="number" min="1" defaultValue="1" placeholder="Quantity" className="rounded-xl border px-4 py-3"/><input name="coupon" placeholder="Coupon code (optional)" className="rounded-xl border px-4 py-3"/><textarea name="address" required placeholder="Full delivery address" className="min-h-28 rounded-xl border px-4 py-3 md:col-span-2"/><button disabled={loading} className="rounded-xl bg-[#1f6b3b] px-6 py-3 font-bold text-white disabled:opacity-50 md:col-span-2">{loading ? 'Processing…' : 'Place COD Order'}</button></form>{message && <div className="mt-5 rounded-xl bg-[#edf5e9] p-4 font-semibold text-[#14502a]">{message}</div>}</div></main>;
}
