/*
# Add master admin support, audit logging, and customer account management

## Summary
This migration adds:
1. A `role` column to `admin_users` to distinguish MASTER_ADMIN from NORMAL_ADMIN
2. An `admin_audit_log` table to record all admin actions on customer accounts
3. A `must_change_password` flag on `auth.users` (via raw_app_meta_data) controlled through edge functions
4. RLS policies on `admin_audit_log` so only authenticated admins can read/insert

## New Tables
- `admin_audit_log`
  - `id` (uuid, PK)
  - `admin_user_id` (uuid, references auth.users) — the admin who performed the action
  - `admin_email` (text) — admin's email for readability
  - `target_user_id` (uuid, references auth.users) — the customer affected
  - `target_email` (text) — customer's email for readability
  - `action` (text) — e.g. 'set_temp_password', 'send_reset_link', 'force_password_change', 'unlock_account'
  - `details` (jsonb) — non-sensitive metadata only; NEVER contains passwords or hashes
  - `created_at` (timestamptz)

## Modified Tables
- `admin_users`: added `role` column (text, default 'admin') — values: 'master_admin' or 'admin'

## Security
- RLS enabled on `admin_audit_log`
- Only authenticated users who are admins can SELECT
- Only authenticated admins can INSERT (the edge function inserts using service role)
- The `must_change_password` flag is stored in `auth.users.raw_app_meta_data` — user-immutable, only writable by the service role
- Temporary passwords are NEVER stored in the database or audit log — only the secure hash is stored by Supabase Auth

## Important Notes
1. Temporary passwords are generated by the edge function, set via the Supabase Auth Admin API (service role), and returned to the admin ONLY in the HTTP response. They are never persisted in any table.
2. The `must_change_password` flag in `raw_app_meta_data` is checked client-side after login to force a password change screen.
3. The audit log records the action type and admin info but NEVER the temporary password itself.
*/

-- 1. Add role column to admin_users
ALTER TABLE admin_users ADD COLUMN IF NOT EXISTS role text NOT NULL DEFAULT 'admin';

-- 2. Create admin_audit_log table
CREATE TABLE IF NOT EXISTS admin_audit_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  admin_email text NOT NULL,
  target_user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  target_email text,
  action text NOT NULL,
  details jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 3. Enable RLS on admin_audit_log
ALTER TABLE admin_audit_log ENABLE ROW LEVEL SECURITY;

-- 4. Policies: only admins can read audit logs
DROP POLICY IF EXISTS "admins_read_audit_log" ON admin_audit_log;
CREATE POLICY "admins_read_audit_log"
  ON admin_audit_log FOR SELECT
  TO authenticated
  USING (EXISTS (SELECT 1 FROM admin_users WHERE admin_users.user_id = auth.uid() AND admin_users.is_active = true));

-- 5. Policies: admins can insert audit logs
DROP POLICY IF EXISTS "admins_insert_audit_log" ON admin_audit_log;
CREATE POLICY "admins_insert_audit_log"
  ON admin_audit_log FOR INSERT
  TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM admin_users WHERE admin_users.user_id = auth.uid() AND admin_users.is_active = true));

-- 6. Index for common queries
CREATE INDEX IF NOT EXISTS idx_audit_log_target ON admin_audit_log(target_user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_admin ON admin_audit_log(admin_user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_created ON admin_audit_log(created_at DESC);

-- 7. Helper function: is_master_admin
CREATE OR REPLACE FUNCTION is_master_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1 FROM admin_users
    WHERE user_id = auth.uid() AND is_active = true AND role = 'master_admin'
  );
$$;
