-- Ads quantity offer price is the total package price. Keep the order item line total
-- equal to that package price and store an average per-packet unit price.
CREATE OR REPLACE FUNCTION public.create_offer_order(p_landing_page_id uuid, p_product_id uuid, p_quantity integer DEFAULT 1, p_bundle_id uuid DEFAULT NULL::uuid, p_customer_name text DEFAULT NULL::text, p_customer_phone text DEFAULT NULL::text, p_delivery_address text DEFAULT NULL::text, p_delivery_zone_id uuid DEFAULT NULL::uuid, p_special_instructions text DEFAULT ''::text, p_order_source text DEFAULT 'ads'::text, p_user_id uuid DEFAULT NULL::uuid, p_utm_source text DEFAULT NULL::text, p_utm_medium text DEFAULT NULL::text, p_utm_campaign text DEFAULT NULL::text, p_utm_content text DEFAULT NULL::text, p_utm_term text DEFAULT NULL::text, p_fbclid text DEFAULT NULL::text, p_gclid text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_order_id uuid; v_order_num text; v_qty integer; v_offer_price numeric; v_compare_price numeric:=0; v_delivery_charge numeric:=0; v_subtotal numeric:=0; v_product_name text; v_stock integer; v_free_delivery boolean:=false; v_offer_id uuid; v_tiers jsonb; v_tier jsonb; v_country text:=public.current_visitor_country();
begin
if p_landing_page_id is null or p_product_id is null then raise exception 'Landing page and product are required'; end if;
if p_customer_name is null or btrim(p_customer_name)='' then raise exception 'Customer name is required'; end if;
if p_customer_phone is null or btrim(p_customer_phone)='' then raise exception 'Customer phone is required'; end if;
if p_delivery_address is null or btrim(p_delivery_address)='' then raise exception 'Delivery address is required'; end if;
if not exists(select 1 from public.landing_pages lp where lp.id=p_landing_page_id and lp.product_id=p_product_id and coalesce(lp.is_active,true)=true and lower(coalesce(lp.status,'active'))='active' and upper(coalesce(lp.country_code,'BD'))=upper(v_country)) then raise exception 'Offer is unavailable'; end if;
select case when p.sale_price is not null and p.sale_price>0 and p.sale_price<p.regular_price then p.sale_price else p.regular_price end,coalesce(nullif(p.name_bn,''),nullif(p.name_en,''),'Product'),p.stock into v_subtotal,v_product_name,v_stock from public.products p where p.id=p_product_id and p.is_active=true and upper(coalesce(p.country_code,'BD'))=upper(v_country) for update;
if not found then raise exception 'Product is unavailable'; end if;
if p_bundle_id is not null then select quantity,bundle_price,compare_price,free_delivery into v_qty,v_offer_price,v_compare_price,v_free_delivery from public.bundle_offers where id=p_bundle_id and product_id=p_product_id and is_active=true and upper(coalesce(country_code,'BD'))=upper(v_country); if not found then raise exception 'Bundle offer is unavailable'; end if;
else v_qty:=coalesce(p_quantity,1); if v_qty<=0 then raise exception 'Invalid offer quantity'; end if; select id,quantity,offer_price,compare_price,free_delivery into v_offer_id,v_qty,v_offer_price,v_compare_price,v_free_delivery from public.quantity_offers where landing_page_id=p_landing_page_id and product_id=p_product_id and quantity=v_qty and is_active=true and upper(coalesce(country_code,'BD'))=upper(v_country) order by display_order asc,created_at asc limit 1;
if not found then select coalesce(lp.pricing_tiers,lp.tiers,lp.quantity_pricing,lp.tier_pricing,'[]'::jsonb) into v_tiers from public.landing_pages lp where lp.id=p_landing_page_id and upper(coalesce(lp.country_code,'BD'))=upper(v_country); select tier into v_tier from jsonb_array_elements(case when jsonb_typeof(v_tiers)='array' then v_tiers else '[]'::jsonb end) as tier where coalesce((tier->>'quantity')::integer,-1)=v_qty limit 1; if v_tier is null then raise exception 'Offer tier is unavailable'; end if; v_offer_price:=coalesce((v_tier->>'offer_price')::numeric,(v_tier->>'price')::numeric); v_compare_price:=coalesce((v_tier->>'compare_price')::numeric,(v_tier->>'regular_price')::numeric,0); v_free_delivery:=coalesce((v_tier->>'free_delivery')::boolean,false) or coalesce((v_tier->>'is_free_delivery')::boolean,false); end if; end if;
if v_qty<=0 or v_offer_price is null or v_offer_price<=0 then raise exception 'Invalid offer pricing'; end if;
if v_stock is null or v_stock<v_qty then raise exception 'Insufficient stock for offer'; end if;
v_delivery_charge:=public.calculate_delivery_charge(v_offer_price,v_free_delivery); v_order_num:=case when upper(v_country)='IN' then 'GS-IN-' else 'GS-BD-' end||upper(substring(replace(gen_random_uuid()::text,'-','') from 1 for 8)); v_subtotal:=v_offer_price;
insert into public.orders(order_number,country_code,user_id,customer_name,customer_phone,delivery_address,customer_address,delivery_zone_id,delivery_zone_name,delivery_charge,shipping_fee,subtotal,discount,discount_amount,total_amount,grand_total,final_amount,payment_method,payment_status,order_source,order_status,status,special_instructions,landing_page_id,utm_source,utm_medium,utm_campaign,utm_content,utm_term,fbclid,gclid,items,cart_items) values(v_order_num,v_country,p_user_id,p_customer_name,p_customer_phone,p_delivery_address,p_delivery_address,null,null,v_delivery_charge,v_delivery_charge,v_subtotal,0,0,v_subtotal,v_subtotal+v_delivery_charge,v_subtotal+v_delivery_charge,'cod','unpaid',coalesce(p_order_source,'ads'),'pending','pending',coalesce(p_special_instructions,''),p_landing_page_id,p_utm_source,p_utm_medium,p_utm_campaign,p_utm_content,p_utm_term,p_fbclid,p_gclid,jsonb_build_array(jsonb_build_object('product_id',p_product_id,'quantity',v_qty,'unit_price',round(v_offer_price / v_qty, 2),'total_price',v_offer_price,'offer_price',v_offer_price)),jsonb_build_array(jsonb_build_object('product_id',p_product_id,'quantity',v_qty,'unit_price',round(v_offer_price / v_qty, 2),'total_price',v_offer_price,'offer_price',v_offer_price))) returning id into v_order_id;
insert into public.order_items(order_id,product_id,product_name,quantity,unit_price,total_price,bundle_id) values(v_order_id,p_product_id,v_product_name,v_qty,round(v_offer_price / v_qty, 2),v_offer_price,p_bundle_id);
update public.products set stock=stock-v_qty,updated_at=now() where id=p_product_id and is_active=true and stock>=v_qty and upper(coalesce(country_code,'BD'))=upper(v_country); if not found then raise exception 'Insufficient stock for offer'; end if;
insert into public.inventory_history(product_id,quantity_change,reason) values(p_product_id,-v_qty,'Offer order '||v_order_num);
update public.landing_pages set conversions=coalesce(conversions,0)+1,updated_at=now() where id=p_landing_page_id and upper(coalesce(country_code,'BD'))=upper(v_country);
return jsonb_build_object('success',true,'order_id',v_order_id,'order_number',v_order_num,'subtotal',v_subtotal,'delivery_charge',v_delivery_charge,'grand_total',v_subtotal+v_delivery_charge,'quantity',v_qty,'offer_price',v_offer_price,'compare_price',v_compare_price);
exception when others then return jsonb_build_object('success',false,'error',SQLERRM); end;
$function$

